Softy_web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, URLResolver

urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, URLPattern, include
from rest_framework import routers

from main import views
from main.views import PostViewSet

app_name = 'main'

# роутеры
router = routers.DefaultRouter()
router.register(r'posts', PostViewSet, basename='posts')

# Основные пути
urlpatterns: list[URLPattern] = [
    path("", views.index, name="index"),
]

# Запросы к api
urlpatterns += [
    path('api/', include(router.urls)),
]

users/urls.py
from django.urls import path, URLPattern, include
from rest_framework import routers

from users import views

app_name = 'users'

# роутеры
router_auth = routers.DefaultRouter()
router_user = routers.DefaultRouter()
router_auth.register(r'auth', views.AuthViewSet, basename='auth')
router_user.register(r'users', views.UserViewSet, basename='users')

# Основные пути
urlpatterns: list[URLPattern] = [

    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/change/", views.profile_change, name="profile_change"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

# Запросы к api
urlpatterns += [

    path('api/', include(router_auth.urls)),
    path('api/', include(router_user.urls)),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="icon" href="{% static "images/icon.jpg" %}">
    {% block css %}{% endblock %}
    <title>{{ title }}</title>
</head>
<body>
<div class="parent">
    <div class="left-column">
        <div class="div-logo">
            <a href="{% url 'main:index' %}" class="softy-logo">Softy</a>
        </div>
        <div id="left-column-content" class="left-column-content">

            {% if request.user.is_authenticated %}
                <div class="profile-div">
                    <img id="user_avatar" src="#"
                         alt="profile_image"
                         class="img_profile">
                    {# в base.js создаётся тег "a" для перехода на страницу профиля текущего пользователя #}
                </div>
            {% else %}
                <div class="profile-div">
                    <a href="{% url 'user:login' %}" id="login-a">Авторизация</a>
                    <a href="{% url 'user:register' %}" id="register-a">Регистрация</a>
                </div>
            {% endif %}

            {% if request.user.is_authenticated %}
                <div id="left-column-content-a" class="left-column-content-a">
                    <a id="btn-your-likes" href="{% url 'main:index' %}">Лента новостей</a>
                    <a id="btn-exit" href="{% url 'user:logout' %}">Выйти</a>
                </div>
            {% endif %}

        </div>
    </div>
    <div class="right-column-parent">
        <div class="right-column">

            {% block up_panel %}{% endblock %}

            <div id="right-column-content" class="right-column-content">
                {% block content %}{% endblock %}
            </div>

        </div>
    </div>
</div>

{% block js %}{% endblock %}

<script src="{% static "js/base.js" %}"></script>

</body>
</html>